blank_issues_enabled: false
contact_links:
  - name: Sights Development Website
    url: https://www.sights.dev
    about: For general questions (not bug reports, feature requests or questions directly related to Sights software), feel free to comment on any relevant blog post for a swift response by a team member.
  - name: Semi Autonomous Productions
    url: https://www.semiautonomous.org
    about: The team behind Sights
